In [ ]:
# SUPERVISED MACHINE LEARNING
# Simple Linear Regression
# First Project: Predict Student Marks On the Basis of the Number of Hours Studied
# Linear Regression is a basic and commonly used type of predictive analysis.
# Linear Regression is an attempt to model the relationship between two variables by fitting
# a linear equation to observed data.

In [57]:
from google.colab import files
upload = files.upload()

Saving Grade_Set_1.csv to Grade_Set_1 (2).csv


In [16]:
!ls

'Grade_Set_1 (1).csv'   Grade_Set_1.csv   sample_data


In [58]:
# Step 1: Data Gathering
# Load The Dataset

import pandas as pd
data = pd.read_csv('Grade_Set_1.csv')
data

Hours_Studied  Test_Grade Status Result
0              2          57   fail      D
1              3          66   fail      D
2              4          73   pass      C
3              5          76   pass      C
4              6          79   pass      C
5              7          81   pass      B
6              8          90   pass      B
7              9          96   pass      A
8             10         100   pass      A

In [24]:
# BasiC Data Exploration
data.columns

Index(['Hours_Studied', 'Test_Grade', 'Status', 'Result'], dtype='object')

In [25]:
data.shape

(9, 4)

In [ ]:
# Step 2 : Data Preparation
# 1.) Check For Missing Values
# 2.) Convert Categorical Values / Non Numerical Into Numerical Features
# 3.) Normalization
# 4.) Select Dependent And Independent Variable

In [28]:
data.isnull().sum()

Hours_Studied    0
Test_Grade       0
Status           0
Result           0
dtype: int64

In [30]:
# Convert categorical into numerical features
from sklearn.preprocessing import LabelBinarizer
# create an object for LabelBinarizer Class
lb = LabelBinarizer()
data.Status = lb.fit_transform(data.Status)

In [31]:
data

Hours_Studied  Test_Grade  Status Result
0              2          57       0      D
1              3          66       0      D
2              4          73       1      C
3              5          76       1      C
4              6          79       1      C
5              7          81       1      B
6              8          90       1      B
7              9          96       1      A
8             10         100       1      A

In [ ]:
# Normalization
# Changing the scale of a mutltiple variable into a same range [0-1]
# Why normalization is necessary for machine learning ?
# MIN-MAX Scaling
# Xnorm = (X - XMIN) / (XMAX - XMIN)
# X = 100
# XMIN = 57
# XMAX = 100

In [38]:
# Select Dependent(y) And Independent Variable(x)
import numpy as np
X = data.Hours_Studied.values
X = X.reshape(9,1) 

In [40]:
X

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [41]:
Y = data.Test_Grade.values
Y

array([ 57,  66,  73,  76,  79,  81,  90,  96, 100])

In [42]:
# Step 3 : Train The Dataset
# Choose a model --> Simple Linear Regression
# Y` = mX + c
# where ,
#         Y` --> Predicted Values
#         m  --> slope/coefficient [Change in the value of Y w.r.t  X]
#         X  --> Independent Variable
#         c  --> intercept [Value of Y when X is zero]

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()

In [43]:
lin_reg.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [44]:
# Print Predicted Values
predicted_values = lin_reg.predict(X)
predicted_values

array([59.71111111, 64.72777778, 69.74444444, 74.76111111, 79.77777778,
       84.79444444, 89.81111111, 94.82777778, 99.84444444])

In [45]:
data['predicted_values'] = predicted_values
data[['predicted_values','Test_Grade']]

predicted_values  Test_Grade
0         59.711111          57
1         64.727778          66
2         69.744444          73
3         74.761111          76
4         79.777778          79
5         84.794444          81
6         89.811111          90
7         94.827778          96
8         99.844444         100

In [49]:
# Evaluate Model Performance
from sklearn.metrics import r2_score
accuracy = r2_score(Y,predicted_values)
print("Accuracy :",accuracy)
print("Accuracy :",accuracy*100,'%')

Accuracy : 0.9757431074095347
Accuracy : 97.57431074095348 %


In [55]:
# Final Prediction
hrs = float(input('Enter Number Of Hours Studied : '))
marks = lin_reg.predict([[hrs]])  # [[]] # 2D array
print('Student who studies for',hrs,'hours will going to score',marks,'marks.')

Enter Number Of Hours Studied : 5
Student who studies for 5.0 hours will going to score [74.76111111] marks.
